from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from .bundle import load_bundle
from .domain import domain_summary


def write_screen_report(
    input_csv: str | Path,
    output_html: str | Path,
    title: str = "MICA Screening Report",
    domain_csv: str | Path | None = None,
    bundle_dir: str | Path | None = None,
) -> Path:
    df = pd.read_csv(input_csv)
    out = Path(output_html).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    numeric = df.select_dtypes(include="number").columns.tolist()
    summary = df[numeric].describe().round(4).to_html(classes="mica-table") if numeric else ""
    preview = df.head(100).to_html(index=False, classes="mica-table")
    model_cols = [col for col in ["mica_model_id", "mica_learner", "mica_feature_layer", "mica_version"] if col in df.columns]
    model_from_output = {col: str(df[col].dropna().iloc[0]) for col in model_cols if not df[col].dropna().empty}
    metadata = {}
    if bundle_dir:
        metadata = load_bundle(bundle_dir).metadata
    domain = domain_summary(domain_csv) if domain_csv else {}
    domain_html = pd.DataFrame([domain]).to_html(index=False, classes="mica-table") if domain else "<p>No domain audit file supplied.</p>"
    model_card = {
        "model_from_output": model_from_output,
        "bundle_metadata": {
            key: metadata.get(key)
            for key in [
                "model_id",
                "learner",
                "feature_layer",
                "feature_count",
                "endpoint",
                "algorithm",
                "ood_protocol",
                "recommended_use",
            ]
            if key in metadata
        },
    }
    model_html = pd.DataFrame([model_card["bundle_metadata"] or model_from_output]).to_html(index=False, classes="mica-table")
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 40px; color: #1f2328; }}
    h1 {{ letter-spacing: -0.03em; }}
    .meta {{ color: #57606a; margin-bottom: 24px; }}
    .mica-table {{ border-collapse: collapse; width: 100%; margin: 18px 0; font-size: 13px; }}
    .mica-table th, .mica-table td {{ border: 1px solid #d0d7de; padding: 6px 8px; text-align: left; }}
    .mica-table th {{ background: #f6f8fa; }}
    code {{ background: #f6f8fa; padding: 2px 4px; border-radius: 4px; }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">Generated by MICA from <code>{Path(input_csv).name}</code>. Rows: {len(df)}</div>
  <h2>Model Card</h2>
  {model_html}
  <h2>Applicability Domain Summary</h2>
  {domain_html}
  <h2>Numeric Summary</h2>
  {summary}
  <h2>Preview</h2>
  {preview}
</body>
</html>
"""
    out.write_text(html, encoding="utf-8")
    sidecar = out.with_suffix(".json")
    sidecar.write_text(
        json.dumps(
            {
                "title": title,
                "input": str(Path(input_csv).expanduser().resolve()),
                "rows": int(len(df)),
                "model_card": model_card,
                "domain_summary": domain,
            },
            indent=2,
            ensure_ascii=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return out
